# примеры API-запросов

# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json

###
# создание объявления
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token faf2d9303225dfa81b5fda8db6c1e8754ee92bd7

{
  "title": "Шторы IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token 86b7b172c4f4ba3df76033004cddeef263e206be

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET http://localhost:8000/api/advertisements/?created_at_after=2020-10-01
Content-Type: application/json

###

DELETE  http://localhost:8000/api/advertisements/9/
Content-Type: application/json
Authorization: Token faf2d9303225dfa81b5fda8db6c1e8754ee92bd7
